server:
  port: 1111
spring:
  datasource:
    url: jdbc:mysql://${LOCAL-HOST:192.168.2.81}:3306/yanbing?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.2.65
    password: 123456
  data:
    mongodb:
      uri: mongodb://192.168.2.84/yanbing
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #设置创建表的引擎为InnoDB

  devtools:
    livereload:
      enabled: true #是否支持livereload
      port: 35729
    restart:
      enabled: true #是否支持热部署
  http:
    encoding:
      charset: utf-8
      force-request: true
      force: true
  aop:
    auto: true
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: debug
